### PR TITLE
Backport backup ui from v2

### PR DESCRIPTION
**Pull request by suphon-t**

### CODE REVIEW

**Comment by divadsn** [comment]
Travis ffs, shut up.

**Review by nyancrimew — APPROVED** [review]
Works (even on EMUI 😮)

**Comment by nyancrimew** [comment]
Waiting for @divadsn's review :) you're free to merge after that

**Comment by divadsn** [comment]
@deletescape tested across different package names?

**Comment by nyancrimew** [comment]
@divadsn That I forgot to do

**Comment by bohrabhijeet** [comment]
@deletescape ok

**Pull request merged**
