### PR TITLE
Please add blur option

### PR DESCRIPTION
**Pull request by Pandemic-XDA**
For apptray background and recent task

### CODE REVIEW

**Comment by gotenksIN** [comment]
Yet another feature request that's a pull request for some reason. Nice

**Comment by RikKoedoot** [comment]
1, use issues for feature requests
2, told you before that all old features are coming to v11, no need to request those.

**Comment by Pandemic-XDA** [comment]
> 1, use issues for feature requests
> 2, told you before that all old features are coming to v11, no need to request those.

Oke sorry i thought feature request was for that and why you sound always so mad ? Calm down oke all cool 😎

Doe maar ff rustig kerel bedoel het ook niet zo.

**Comment by Pandemic-XDA** [comment]
And btw why it take ages to add 1 thing -___-"

**Comment by gotenksIN** [comment]
image

**Pull request closed without merging**
