### PR TITLE
 Let's give freedom to everyone!

### PR DESCRIPTION
**Pull request by divadsn**
Don't hide smiles in the app drawer anymore, everyone happy now. :smile:

### CODE REVIEW

**Comment by cantsingh** [comment]
lol

**Comment by DatDucati** [comment]
This is bad practice. It's none of the launchers business which apps I've installed on my device.

**Comment by divadsn** [comment]
@DasBiest: It's our business to prevent unauthorized use of iconpacks.

Just like Substratum is keeping you away from using pirated themes for example.

**Comment by tills13** [comment]
> It's our business to prevent unauthorized use of iconpacks.

I'm not sure I follow this. Your product is a launcher - kind of a "dumb-pipe" to use other applications on the device.

> Substratum is keeping you away from using pirated themes for example

Not sure I agree with this either. Two wrongs don't make a right. 

I appreciate the sentiment, but I disagree with the execution. I should be able to choose which apps show up or don't - it doesn't matter who they are from or how I got them.

**Comment by divadsn** [comment]
@tills13 iconpacks are a feature of our launcher and currently we allow anyone to use any iconpack they want, from any source, no matter if paid or free.

The problem is the following one, iconpack developers don't have an option right now to protect the unauthorized use of their iconpacks when these aren't legally purchased on the Google Play store. So in order to prevent them from doing it now, I added a check with a polite message about the fact that you might wanna uninstall these apps in order to use these iconpacks. It still won't check if these iconpacks were purchased, but it's currently impossible without changes in the way the iconpacks work for now.

We hope to see some of the major iconpack templates to add a license check hook, which we can call when the user have selected that iconpack, so we can decide whether deny or allow applying the selected iconpack. But I guess it will take some time...

**Comment by divadsn** [comment]
@tills13 
> I appreciate the sentiment, but I disagree with the execution. I should be able to choose which apps show up or don't - it doesn't matter who they are from or how I got them.

We don't hide them anymore.

**Comment by KieronQuinn** [comment]
Any idea why "com.android.protips" is blocked? As far as I can tell it's only been used for the old protips widget in Android: [this one](https://developer.android.com/sdk/images/2.2/22home.png)

**Comment by divadsn** [comment]
@KieronQuinn: Don't ask me, I haven't created that list, but this package name won't even appear on Android versions which Lawnchair does support, so I guess is more likely a malware/piracy app hiding beneath that package name. (Like Lucky Patcher does, but with a different ending)

**Comment by nicholaschum** [comment]
I see our list. Haha.

**Comment by clairekardas** [comment]
@nicholaschum Till, Harsh and I indeed took the Substratum list and used that for Lawnchair, we basically have the same list now since my PR got merged to the template too. That went kind of unnoticed tho.

**Comment by beatbrot** [comment]
To be completely honest: Do not overestimate your power. I do understand that you are happy, Lawnchair is taking off. But playing with your power by adding restrictions to fellow users? 
Or by providing "hooks" for icon-pack creators even tough Lawnchair doesnt remotely covers any relevant userbase?

I (and I guess many others) like Lawnchair because of the idea of freedom. Because it is open source. And also because it does what it should do: Launch apps and look nice while doing it. Do not destroy that image by weird restrictions

**Comment by guest4711** [comment]
I never had  used any of the blacklisted apps til today and I do not think I will do. But I really don't like the idea to be restricted which apps I install or how I name them. 
To say it in German words: "Wehret den Anfängen!"

**Comment by divadsn** [comment]
@beatbrot: If you don't like our changes then be free to create your own builds of "pirate" Lawnchair. :wink:

@guest4711: we are not restricting you anymore from using these blacklisted apps tho...

**Comment by YUDHPK** [comment]
Thanks for reverting

**Comment by YUDHPK** [comment]
Regarding icon pack issue
As someone suggested you could display notification regarding the issue once in a day to those people who use unlicensed icon packs.
That would both inform them and piss them off.

Also whenever people use icon from such icon pack you could display pirate icon in small like what you do with app shortcuts (where we display app icon)

**Comment by rodjun** [comment]
Yeah because being annoying will really make people rethink their attitudes, they totally won't just uninstall law chair or install some fork with that bullshit disabled. Are you guys are new to the internet or something? I understand the good intentions but that is simple not how things work. 

Just be a launcher, not some kind of moral police.

**Comment by ACHOKAMAN** [comment]
Just always remember this is a launcher not substratum,,how many substratum are their??almost 0 and how many launcher are their that offer same functionality.. enough... people have the power too... democracy matters.

**Comment by guest4711** [comment]
@divadsn: Thanks. Well done.

**Comment by leetdavid** [comment]
I usually disagree with censorship, but the changes are literally being made in public. If you dislike what the devs are doing, fork the repo yourself and make your own version.

The devs could also be a bit more mature about their responses.

**Comment by tills13** [comment]
> If you dislike what the devs are doing, fork the repo yourself and make your own version.

isn't the point for a lot of people - most of us just want a plug-and-play launcher and not have to maintain it ourselves.

**Comment by leetdavid** [comment]
> isn't the point for a lot of people - most of us just want a plug-and-play launcher and not have to maintain it ourselves.

I also don't want the launcher to butt in and tell me what to do or not do, but we're not paying the devs so they honestly can do what they want.
If you want a plug-and-play solution, buy Nova Launcher Premium. Support the devs.

**Comment by ACHOKAMAN** [comment]
@KarmaQueen do you make your apps for the people or the developers?? It taught people opinions matter??if they are not comfortable with the new update you tell them to make their own or what???.... people where not happy with the update it is ok if they say it and atleast devs to listen to them coz at the end of the day they are the consumers of your product... don't tell them to make choice...if it were one person them ok but numerous number of people are complaining  then they are pissed

**Pull request merged**
