### PR TITLE
Use mrmans0n Compose rules to check styles

### PR DESCRIPTION
**Pull request by Goooler**
## Description

https://mrmans0n.github.io/compose-rules/rules/#hoist-all-the-things
https://mrmans0n.github.io/compose-rules/rules/#ordering-composable-parameters-properly
https://mrmans0n.github.io/compose-rules/rules/#avoid-using-unstable-collections
https://mrmans0n.github.io/compose-rules/rules/#modifiers-should-be-used-at-the-top-most-layout-of-the-component
https://mrmans0n.github.io/compose-rules/rules/#do-not-emit-multiple-pieces-of-content
https://mrmans0n.github.io/compose-rules/rules/#compositionlocals
https://mrmans0n.github.io/compose-rules/rules/#when-should-i-expose-modifier-parameters

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by MrSluffy** [comment]
Have you tried the build apk? Seems I can't touch anything in settings

**Comment by Goooler** [comment]
You are right, will take a look later.

**Comment by MrSluffy** [comment]
I just test the build apk, can't touch any settings entry . I just switched to A14, can you confirm in your end. Thanks

**Comment by Goooler** [comment]
It already works.

**Comment by MrSluffy** [comment]
Yeah works, now in build 59

**Comment by Goooler** [comment]
@SuperDragonXD Any idea?

**Review by SuperDragonXD — COMMENTED** [review]
Do we really need to add modifiers for *all* the components (especially the screen/destination components)? I feel like it's not needed, especially since most of them are unused/don't do anything.

**Comment by Goooler** [comment]
See https://chrisbanes.me/posts/always-provide-a-modifier.

**Review by MrSluffy — APPROVED** [review]

**Comment by SuperDragonXD** [comment]
> See https://chrisbanes.me/posts/always-provide-a-modifier.

Even then, most of the modifiers here modify nothing:
```kotlin
@Composable
fun Example(modifier: Modifier = null) {
  SomeComponent()
}
```

If we still plan on changing it, I'd recommend use the `modifier` to modifier either the `Surface`, `PreferenceLayout`, etc. Otherwise, it is just a useless parameter.

**Comment by Goooler** [comment]
I'm turning it off in 1d7b28ebd9c6c4583d610d99ea7152b615ffce54.

**Review by SuperDragonXD — APPROVED** [review]

**Pull request merged**
