### PR TITLE
Copy calculator search result to clipboard

### LINKED ISSUE #4729: [FEATURE] Calculator copy on interaction
### Describe the feature

It would be very convenient if tapping on the App Drawer's Search Calculator result would copy the result to clipboard.

### Why would it be useful to add?

Convenience, usability, speed.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Don't have any code, but here's a [video](https://github.com/user-attachments/assets/71e13153-35c9-4a09-ac4a-caa0631bea87).

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by tgex0**
## Description

New feature to copy the calculator search result to the clipboard (by just tapping the calculator search result tile).

Fixes #4729

## TODO
~1. Revert icon to regular _calculator.xml_ (reference in _SearchTargetFactory.kt_)~
~2. Add _ic_copy.xml_ icon to right-hand side of calculator search result tile~

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by tgex0** [comment]
Basic functionality works fine but there is no indication that tapping the tile will copy the result to the clipboard. Maybe this is fine as it is.

Rather than adding text somewhere or a further icon, I thought the least intrusive solution might be to change the calculator icon to a combo calculator/copy-to-clipboard icon. Something like this:

icon

Please let me know what you think. Thanks.

**Comment by SuperDragonXD** [comment]
I'd suggest to add an icon to copy the result to the clipboard (at the right side), as it makes it significantly clear that you can copy the result.

**Comment by tgex0** [comment]
I agree but, unfortunately, I could not figure out how to do that.

**Comment by SuperDragonXD** [comment]
I guess we can make the icon a temporary solution as of now (make sure to mark it as `TODO`).

**Comment by tgex0** [comment]
OK, I've added and implemented the new combo icon and added a TODO in this PR's description.

**Comment by tgex0** [comment]
I'll leave this in draft mode as I need to fix the icon...

**Comment by tgex0** [comment]
Icon is probably OK. I think the problem I experienced with it may be due to #4807.

**Comment by tgex0** [comment]
Icon not displaying correctly (in Dark theme) is due to #4813. (No problem with icon. Problem was with backup file.)

**Comment by tgex0** [comment]
TODO tasks complete.

**Review by SuperDragonXD — APPROVED** [review]
Hello again, and thanks for your patience.

While this solution isn't exactly elegant, it works for the purpose of showing single that the text is copyable. I'd probably refactor this (alongside other related code) after some time.

**Comment by tgex0** [comment]
Just for clarification, I was able to include the regular clipboard icon at the right-hand side of the calculator results tile as you suggested (via a new layout) and the current PR reflects this. I reverted the calculator icon to the original one.

Screenshot

I hope that's OK.

**Comment by MrSluffy** [comment]
Hi can you update this to `15-dev` Thanks!

**Review by MrSluffy — APPROVED** [review]

**Pull request merged**
