### PR TITLE
Allow resizing any widget

### PR DESCRIPTION
**Pull request by LinuxLlama**
Title says it all. Allows any widget to be resized without being restricted on Lawnchair 2.0.

### CODE REVIEW

**Comment by LinuxLlama** [comment]
Don't worry about the "Add font file" and "Delete font" commits, those were early tests for a different project.

**Comment by divadsn** [comment]
Before merging this, please check any shit widgets from Samsung and Huawei.

**Comment by skittles9823** [comment]
@divadsn

**Comment by divadsn** [comment]
@skittles9823 u w0t m8, do some productive activity.

**Comment by skittles9823** [comment]
@divadsn

**Comment by LinuxLlama** [comment]
@divadsn Motorola widgets work. I'll test Samsung widgets now.

Edit: Samsung widgets work fine

**Comment by LinuxLlama** [comment]
Codacy is probably upset due to adding a simple space to the code. Build works fine so it shouldn't be a problem.

**Comment by divadsn** [comment]
Leaving this to @paphonb as he is working mainly on v2 for now.

**Review by suphon-t — APPROVED** [review]

**Pull request merged**
