### PR TITLE
Fix OneUI Gesture crash

### PR DESCRIPTION
**Pull request by DanGLVK**

### CODE REVIEW

**Comment by divadsn** [comment]
Any description? Testing?

**Comment by DanGLVK** [comment]
> Any description? Testing?

Was tested by an individual who was trying another fixed version, i built the app from source with the fix and sent it to him to confirm it's working 

https://user-images.githubusercontent.com/32078304/114310772-57110c00-9ac2-11eb-8166-086d699b3857.mp4

**Comment by suphon-t** [comment]
This is weird. The method you added isn't referenced anywhere at all. How does it fix this?

**Comment by DanGLVK** [comment]
> This is weird. The method you added isn't referenced anywhere at all. How does it fix this?

Fact is, while Lawnchair isn't calling this it seems One UI is, having a blank class seems to be enough to satisfy One UI and not cause it to crash Lawnchair

**Comment by suphon-t** [comment]
Can I look at the crash log once again? On the version without this fix.

**Comment by suphon-t** [comment]
I actually misinterpreted your changes. Can you verify that it still works when compiling with `optimized` variant? I'm worried proguard might strip the method out.

**Comment by DanGLVK** [comment]
> I actually misinterpreted your changes. Can you verify that it still works when compiling with `optimized` variant? I'm worried proguard might strip the method out.

Decompiling the optimized build seems to show the method  is still there.

**Review by suphon-t — APPROVED** [review]

**Pull request merged**
