### PR TITLE
Merge tag 'android-15.0.0_r3'

### LINKED ISSUE #4760: Merge `android15-release` from AOSP
Source code: https://android.googlesource.com/platform/packages/apps/Launcher3/+/refs/heads/android15-release

Potentially breaking changes:
* Private space
* App archiving
* New Quickstep APIs

### PR DESCRIPTION
**Pull request by MrSluffy**
## Description

- Closes #4112.
- Closes #4760.

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:white_check_mark: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by Goooler — APPROVED** [review]
LGTM! This should be merged manually once we get ready.

**Comment by Goooler** [comment]
```
java.lang.ExceptionInInitializerError
  at app.lawnchair.LawnchairApp.<init>(LawnchairApp.kt:59)
  at java.lang.Class.newInstance(Native Method)
  at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
  at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51)
  at android.app.Instrumentation.newApplication(Instrumentation.java:1282)
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1477)
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1414)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7127)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2340)
  at android.os.Handler.dispatchMessage(Handler.java:111)
  at android.os.Looper.loopOnce(Looper.java:242)
  at android.os.Looper.loop(Looper.java:362)
  at android.app.ActivityThread.main(ActivityThread.java:8393)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992)
Caused by: java.lang.RuntimeException: Cannot read value from namespace launcher from DeviceConfig. It could be that the code using flag executed before SettingsProvider initialization. Please use fixed read-only flag by adding is_fixed_read_only: true in flag declaration.
  at com.android.launcher3.FeatureFlagsImpl.load_overrides_launcher(FeatureFlagsImpl.java:144)
  at com.android.launcher3.FeatureFlagsImpl.enableSmartspaceAsAWidget(FeatureFlagsImpl.java:532)
  at com.android.launcher3.Flags.enableSmartspaceAsAWidget(Flags.java:205)
  at com.android.launcher3.Utilities.<clinit>(Utilities.java:180)
  at app.lawnchair.LawnchairApp.<init>(LawnchairApp.kt:59) 
  at java.lang.Class.newInstance(Native Method) 
  at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) 
  at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51) 
  at android.app.Instrumentation.newApplication(Instrumentation.java:1282) 
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1477) 
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1414) 
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7127) 
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2340) 
  at android.os.Handler.dispatchMessage(Handler.java:111) 
  at android.os.Looper.loopOnce(Looper.java:242) 
  at android.os.Looper.loop(Looper.java:362) 
  at android.app.ActivityThread.main(ActivityThread.java:8393) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ContentResolver android.app.Application.getContentResolver()' on a null object reference
  at android.provider.Settings$Config.getContentResolver(Settings.java:19447)
  at android.provider.Settings$Config.getStrings(Settings.java:19061)
  at android.provider.DeviceConfig.getProperties(DeviceConfig.java:1064)
  at com.android.launcher3.FeatureFlagsImpl.load_overrides_launcher(FeatureFlagsImpl.java:66)
  at com.android.launcher3.FeatureFlagsImpl.enableSmartspaceAsAWidget(FeatureFlagsImpl.java:532) 
  at com.android.launcher3.Flags.enableSmartspaceAsAWidget(Flags.java:205) 
  at com.android.launcher3.Utilities.<clinit>(Utilities.java:180) 
  at app.lawnchair.LawnchairApp.<init>(LawnchairApp.kt:59) 
  at java.lang.Class.newInstance(Native Method) 
  at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76) 
  at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:51) 
  at android.app.Instrumentation.newApplication(Instrumentation.java:1282) 
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1477) 
  at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1414) 
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7127) 
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2340) 
  at android.os.Handler.dispatchMessage(Handler.java:111) 
  at android.os.Looper.loopOnce(Looper.java:242) 
  at android.os.Looper.loop(Looper.java:362) 
  at android.app.ActivityThread.main(ActivityThread.java:8393) 
  at java.lang.reflect.Method.invoke(Native Method) 
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) 
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:992) 
```

**Comment by MrSluffy** [comment]
I already have fixed for this but haven't push yet, can you not push right now in this PR? Thanks!

**Comment by Goooler** [comment]
Good job!

**Comment by Goooler** [comment]
This one should be merged manually, repushed!

**Pull request merged**
