### PR TITLE
Remove redundant RestrictionBypass init

### PR DESCRIPTION
**Pull request by Goooler**
## Description

https://github.com/ChickenHook/RestrictionBypass#usage https://github.com/ChickenHook/RestrictionBypass/blob/f0764f1e90ce91b0fe4fdbccc378e0902be71e5a/restrictionbypass/src/main/java/org/chickenhook/restrictionbypass/BypassProvider.java#L50-L54

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by liu-wanshun** [comment]
依赖provider进行初始化，会由于provider加载顺序问题，无法保证unseal第一时间执行，会偶现因为无法访问hidenApi导致崩溃。

**Comment by Goooler** [comment]
那如果把那个 provider 去掉只保留这里呢

**Comment by liu-wanshun** [comment]
可以，我自己项目中就是移除provider，然后自己调用unseal的。

**Comment by Goooler** [comment]
你工作就是开发 launcher 嘛，有兴趣加入 Lawnchair 嘛

**Comment by Goooler** [comment]
你工作就是开发 launcher 嘛，有兴趣加入 Lawnchair 嘛

**Pull request merged**
