### PR TITLE
New about ui

### PR DESCRIPTION
**Pull request by nyancrimew**
This PR will temporarily remove attribution to translators until Attribouter supports something like it.

### CODE REVIEW

**Comment by deletescape** [comment]
@deletescape [DO NOT MERGE]

**Comment by divadsn** [comment]
Will extend the library tomorrow and add along with Twitter handles for us.

**Comment by nyancrimew** [comment]
@divadsn ... Like I told you I made a feature request for that in the library. @TheAndroidMaster is pretty much finished with adding support for more links e.g. twitter handles

**Comment by nyancrimew** [comment]
image
image
image
image
image

**Pull request merged**
