### PR TITLE
Update deps

### PR DESCRIPTION
**Pull request by Goooler**
## Description

https://developer.android.com/jetpack/androidx/releases/compose-ui#1.3.0 
https://developer.android.com/jetpack/androidx/releases/compose-material3#1.0.0
https://developer.android.com/jetpack/androidx/releases/annotation#annotation-1.5.0
https://developer.android.com/jetpack/androidx/releases/activity#1.6.0
https://github.com/google/accompanist/releases/tag/v0.27.0
https://github.com/material-components/material-components-android/releases/tag/1.7.0
https://github.com/google/protobuf-gradle-plugin/releases/tag/v0.9.0

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by yasanglass** [comment]
@Goooler Should I enable dependabot on this repo?

**Review by yasanglass — APPROVED** [review]

**Comment by Goooler** [comment]
> @Goooler Should I enable dependabot on this repo?

I'm afraid it can't handle the version catalogs after we migrating.

**Comment by yasanglass** [comment]
> > @Goooler Should I enable dependabot on this repo?
> 
> I'm afraid it can't handle the version catalogs after we migrating.

We havent added Dependabot for some months due to this now but we also haven migrated to version catalogs. Maybe we should just enable it for now until we migrate to version catalogs and we just deal with the potential issues once we migrate.

**Comment by Goooler** [comment]
OK, do it.

**Pull request merged**
