### PR TITLE
Add option to hide the clock from the status bar when in the home screen

### PR DESCRIPTION
**Pull request by ghost**
The AndroidManifest license removal is due to the manifest not being part of AOSP.

If you’d like me to restore it just let me know

### CODE REVIEW

**Comment by nyancrimew** [comment]
Please for heaven's sake at least look at your diff before blindly pushing and PRing

**Comment by ghost** [comment]
> Please for heaven's sake at least look at your diff before blindly pushing and PRing

This time I looked at the diff 9 different times each time I cherry-picked something over and couldn’t find any issues.

I didn’t even run optimize imports or refactor the code since it obviously would introduce unneeded formatting changes to the code.

**Comment by suphon-t** [comment]
> couldn’t find any issues. 

Would you consider [this](https://github.com/LawnchairLauncher/Lawnchair/pull/1676/files#diff-0957ecb76e97694433030803dad3bbaeR40) a good code?
And that’s from just glancing at the PR because I’m not at home.

**Comment by ghost** [comment]
> > couldn’t find any issues.
> 
> Would you consider [this](https://github.com/LawnchairLauncher/Lawnchair/pull/1676/files#diff-0957ecb76e97694433030803dad3bbaeR40) a good code?
> And that’s from just glancing at the PR because I’m not at home.

Well, it’s scheduled for removal `@Deprecated("No longer used and scheduled for removal")`

It was used to test the status bar code and nothing else, and I soon switched over to using onWindowFocusChanged

**Comment by ghost** [comment]
The only reason it’s still there is some ROMs (MIUI) work properly with clock hiding but don’t actually call onWindowFocusChanged, and I need something to test the preference code

**Pull request closed without merging**
