### PR TITLE
Settings UI facelift.

### PR DESCRIPTION
**Pull request by LinuxLlama**
Made some mistakes like how I deleted files and replaced them instead of just adding the new lines. Other than that, build runs fine and haven't seen any issues.

screenshot aug 19 2017 2-19-50 pm

screenshot_20170821-133513

screenshot_20170821-133522

### CODE REVIEW

**Comment by ArmanKir-yan25** [comment]
With blue color it's more stock

**Comment by ArmanKir-yan25** [comment]
Only thing is to do is change Google Assistant button icon to original

**Comment by nyancrimew** [comment]
How does this look with the dark/black theme?

**Comment by fonix232** [comment]
Could you please fix the padding near the icons? It should be equal to frame and to text (right now, the icon-text distance is visibly much more than the left frame-icon distance). Otherwise, it looks nice. And as @deletescape said, dark/black themes needed.

**Comment by fonix232** [comment]
BTW you can squash your changes and reupload the PR, that way the deleted/etc. files won't appear in history :)

**Comment by franco98silva** [comment]
¿Cómo quedaría con los iconos en Blanco y Negro? Me resulta mucho más amigable este cambio en la interfaz.
-
How does this look with the black & white icons? I find this change in interface much friendly for the standart user.

**Comment by LinuxLlama** [comment]
@fonix232 I have been trying to figure out how to fix that issue. I'm going search up how to fix.

**Comment by LinuxLlama** [comment]
@deletescape Added new images

**Comment by franco98silva** [comment]
Looks great 😎

**Comment by SovsOgKartofler** [comment]
You could do without the separators and let the padding stay as-is (forgive me for opposing you @fonix232 😃  ) which would be more in line with the settings app of Android 8.0.

**Comment by ACHOKAMAN** [comment]
Cute

**Comment by beatbrot** [comment]
Stupid question, but is there any reason why this doesnt get merged? Oo

**Comment by ACHOKAMAN** [comment]
@beatbrot am wandering too.....the dev haven't explained it yet..

**Comment by nyancrimew** [comment]
This will be merged as soon as @Treemindr resolves merge conflicts

**Comment by Treemindr** [comment]
@deletescape Where should I move the strings over to?

**Comment by LinuxLlama** [comment]
@deletescape I have fixed the conflicts.

**Comment by ghost** [comment]
Yay gib clay

**Review by LinuxLlama — COMMENTED** [review]
Not sure whats going on but now the build isn't passing on Travis CI but the build on Android Studio is completely fine...

**Pull request merged**
