### PR TITLE
Dholuo Language Support 

### PR DESCRIPTION
**Pull request by AngelofVerdant**
## Description

I have included support for Dholuo Language, which is one of the major native languages from Kenya. I believe non English speaking   people in my country should also be able to  use Lawnchair

### CODE REVIEW

**Review by Goooler — CHANGES_REQUESTED** [review]
1. You should send this PR to `12.1-dev` branch instead of `12-dev`.
2. Resources should be settled under `lawnchair` dir.
3. Revert the changes in `gradle/wrapper/gradle-wrapper.properties`.

**Comment by AngelofVerdant** [comment]
Noted, will do

**Comment by AngelofVerdant** [comment]
Or rather , It would be much easier to add support for my native language using crowdin. So how would I go about adding my language to crowdin and edit from there?

**Comment by Goooler** [comment]
You have no permission. If you want, I'll address your changes in a new PR.

**Comment by Goooler** [comment]
Addressed to #3174.

**Pull request closed without merging**
