### PR TITLE
Add an item in OptionsPopupView to jump to system settings

### PR DESCRIPTION
**Pull request by Goooler**
## Description

https://user-images.githubusercontent.com/10363352/216339624-ec2e7f15-6704-4a09-ac91-541c7a7f3b13.mp4

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by SuperDragonXD — APPROVED** [review]
I'd suggest adding an option to show/hide that. Some users may not want having that option, although it's up to you.

Otherwise it's fine.

**Comment by Goooler** [comment]
> I'd suggest adding an option to show/hide that.

I was considering that too, not sure if we need to place this option in a new group named "Context Menu" under "Home Screen".

**Comment by SuperDragonXD** [comment]
Sure that's fine. The "lock home screen" button could be placed there too.

**Comment by Goooler** [comment]
> The "lock home screen" button could be placed there too.

Well, just merging this one, I'll do it in a follow-up.

**Pull request merged**
