### PR TITLE
SystemShortcut: Add uninstall option

### PR DESCRIPTION
**Pull request by Jertlok**
This allows to easily uninstall application on the popup
activity triggered by long pressing on the applications.

### CODE REVIEW

**Comment by Jertlok** [comment]
@deletescape, let me know if I shouldn't write this in Java - nevertheless this is worth pushing to DirtyUnicorns Launcher3, so I did not waste my time.

**Comment by nyancrimew** [comment]
We generally do accept Java, and for smaller changes like these I think I wouldn't bother with rewriting in Java either.

**Comment by divadsn** [comment]
I leave that to other team members, as I know that in the past we were rather not liking that.

Edit: "[...] so far we said we kinda don't wanna clutter the menu too much but idk"

**Comment by Jertlok** [comment]
I do understand that, we might move that under the custom edit action, but that wouldn't make too much sense at that point you could juust press on the (i) and uninstall the application with the same amounts of actions :+1:

**Comment by divadsn** [comment]
@Jertlok Or drag the app and move to the "Uninstall" at the top of the screen 😉

**Comment by Jertlok** [comment]
Force pushed as I have noticed that I added the shortcut with the maximum priority, fixed that just in case you will reconsider this shortcut :+1:

**Pull request closed without merging**
