### PR TITLE
Add support for "Pixel Search" app

### PR DESCRIPTION
**Pull request by validcube**
## Description

Motivation:  *I just use this app, "Pixel Search", 5 minutes later, I want this search provider on Lawnchair...*

* Search provider: https://play.google.com/store/apps/details?id=rk.android.app.pixelsearch
* Description: Google Pixel Universal Search, but for everyone

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
✅ New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by Goooler — APPROVED** [review]

**Comment by ghost** [comment]
Yes! I use this as well.

**Comment by Somedudd** [comment]
How do I add it(it's not in the options)

**Comment by KTibow** [comment]
@Somedudd are you on the latest alpha

**Comment by Somedudd** [comment]
I'm on lawnchair 12 alpha 4

**Comment by ghost** [comment]
> I'm on lawnchair 12 alpha 4

Use the dev versions.

**Comment by Somedudd** [comment]
Where do I get them? If it's the debug apks then it's expired if not can you provide a link?

**Comment by ghost** [comment]
> Where do I get them? If it's the debug apks then it's expired if not can you provide a link?
> 

https://www.apkmirror.com/apk/lawnchair/

**Comment by alabotski** [comment]
Hi I have problems

When I tap the search bar it forwards me to Play Store to download Pixel Search (but it's already installed)

**Comment by KTibow** [comment]
Does restarting Lawnchair/your phone help?

**Comment by alabotski** [comment]
@KTibow 
No.

People also have such problems
https://github.com/LawnchairLauncher/lawnchair/issues/3606

**Comment by 2004seraph** [comment]
I think this issue needs to be reopened because this isnt working on a lot of phones, mine included.

**Comment by KTibow** [comment]
@2004seraph it's a pr not an issue 🙃

**Pull request merged**
