### PR TITLE
Dynamic status bar gradient by luminance calculation

### PR DESCRIPTION
**Pull request by saikrishna279**
This is like a switch to turn ON/OFF the annoying white gradient over the status bar area when a dark/black wallpaper is applied. Especially noticeable on LED Displays
It is replaced by a fully transparent background when a dark/black wall is applied
The gradient is shown when a light/bright wallpaper is applied

### CODE REVIEW

**Comment by nyancrimew** [comment]
As we have discussed on Telegram already this white gradient can currently be turned off manually with a switch, but personally think it would be great to replace said switch with your automatic method. But this would require some adjustments to your PR (like removing the switch, etc.)

**Comment by divadsn** [comment]
Imo it's better with a switch, for live wallpapers especially.

**Comment by divadsn** [comment]
As I already mentioned, it would break with live wallpapers, same as with blur.

**Comment by AxiK101** [comment]
Switch indeed

**Pull request closed without merging**
