### PR TITLE
Optimize drawables

### PR DESCRIPTION
**Pull request by Darkstar085**
Before - 627.73kb
After - 546.84kb

Signed-off-by: Sipun Ku Mahanta <sipunkumar85@gmail.com>
Change-Id: I982b546a141b3ec1ddc58758957607f6242f82fb

### CODE REVIEW

**Comment by roge07** [comment]
WOW that's a huge reduction in size

**Comment by roge07** [comment]
unfortunately im just a viewer but hopefully it can merge

**Comment by yasanglass** [comment]
Thanks for contributing, @Darkstar085. Can you just explain how you optimized these images?

**Comment by Darkstar085** [comment]
> Thanks for contributing, @Darkstar085. Can you just explain how you optimized these images?

Its done by using imgbot source code available here - https://github.com/imgbot/Imgbot

**Comment by yasanglass** [comment]
Thank you, @Darkstar085.

**Comment by Goooler** [comment]
> Its done by using imgbot source code available here - https://github.com/imgbot/Imgbot

@yasandev 
And you can enable @Imgbot for lawnchair.

**Comment by yasanglass** [comment]
> @yasandev And you can enable @imgbot for lawnchair.

It says it's for Azure so I didn't look too much into it... but yeah it seems like we can enable it for Lawnchair. I'll look into it, thanks.

**Comment by Darkstar085** [comment]
> > @yasandev And you can enable @imgbot for lawnchair.
> 
> It says it's for Azure so I didn't look too much into it... but yeah it seems like we can enable it for Lawnchair. I'll look into it, thanks.

U can just signup for it..

**Comment by roge07** [comment]
@yasandev i thnk you can do this for lawnicons and reduce the file size by a lot :)

**Comment by yasanglass** [comment]
I don't have enough access to enable it for the repositories. I forwarded the bot link to the people who have.

**Comment by Darkstar085** [comment]
> I don't have enough access to enable it for the repositories. I forwarded the bot link to the people who have.

Nice.. i will do it if u guys add any new images/pics.. np

**Comment by Darkstar085** [comment]
This is for lawnicons but i'm not aure about the svg's so need to test it first - https://github.com/Darkstar085/lawnicons/commit/aa788edb7880f957acbe270b38ab9f9f1f7249e0

**Pull request merged**
