### PR TITLE
Categorized Settings Menu

### PR DESCRIPTION
**Pull request by LinuxLlama**
The title says it all! I moved all the Pixel features into their appropriate category.

screenshot_20171017-203711

### CODE REVIEW

**Comment by LinuxLlama** [comment]
Travis doesn't seem to like my PR again... I'm not too great with coding so some help to fix it would be appreciated!

**Comment by divadsn** [comment]
Travis says this one here: https://travis-ci.org/Deletescape-Media/Lawnchair/builds/289329228#L1368

**Comment by burakdede0** [comment]
Looks amazing

**Comment by burakdede0** [comment]
Can you make "App drawer" instead of "App Drawer"?

**Review by divadsn — APPROVED** [review]
Fixed the failing CI build, now the question is about the seperator, but afaik @paphonb is approving it.

**Comment by divadsn** [comment]
To be merged after #861

**Pull request merged**
