### PR TITLE
Snow

### PR DESCRIPTION
**Pull request by divadsn**

### CODE REVIEW

**Comment by guest4711** [comment]
Very nice, thank you...

**Comment by alekksander** [comment]
@divadsn how about 2019?

**Comment by divadsn** [comment]
I'm busy with university, but maybe next week someone from the team can pull off this work for v2 :)

**Comment by skittles9823** [comment]
@divadsn Till is already working on it for V2 iirc

**Comment by alekksander** [comment]
awesome. hope it's gonna make it to f-droid updated release before Christmas :)

**Pull request merged**
