### PR TITLE
[11 dev] icon change doesn't work right

### PR DESCRIPTION
**Pull request by Pandemic-XDA**
Icon pack changer works not so good on 11 dev build like on lc for a10
Example: when you download glass icon pack by ambor here
https://play.google.com/store/apps/details?id=com.ambor.iconpack
It changes on previous lawnchair but not on the dev 11 build.. Intested it.
Hopefully it can be fixed because on previous version of lc like 9.1 alpha 3 it works fine.

### CODE REVIEW

**Comment by msfjarvis** [comment]
Why did you open a pull request to report a bug?

**Comment by AgentFabulous** [comment]
> Why did you open a pull request to report a bug?

image

Please open an issue, not an invalid pull request.

**Comment by Pandemic-XDA** [comment]
> Why did you open a pull request to report a bug?

Oke my bad i will do that :)

**Comment by Pandemic-XDA** [comment]
> > Why did you open a pull request to report a bug?
> 
> image
> 
> Please open an issue, not an invalid pull request.

Do you guys even look in the issues section ?

**Comment by gotenksIN** [comment]
yes they do, even if they didn't that still doesn't make this the right place

**Pull request closed without merging**
