### PR TITLE
Backport 8.1 Fastscroller [WIP]

### PR DESCRIPTION
**Pull request by nyancrimew**

### CODE REVIEW

**Comment by nyancrimew** [comment]
Currently broken, the fastscroll bar is rendered weirdly and twice

**Comment by LinuxLlama** [comment]
Is this the full scroll bar or just the bubble with the letter?

**Comment by nyancrimew** [comment]
The whole scrollbar implementation changed, so this is a backport of the entire thing

**Comment by nyancrimew** [comment]
8.1 source dropped, there are going to be simpler way to add this

**Pull request closed without merging**
