### PR TITLE
Reduced about 4.5kB from the png's with lossless compression

### PR DESCRIPTION
**Pull request by pagaiba**
I don't even know how. Btw prolly you gonna want to remove the gradle changes but left them cuz I fargot to not add 'em and also it's the latest version and it gud so far so maybe you wanna try it out anywayz

### CODE REVIEW

**Comment by deletescape** [comment]
Undo the gradle changes and I will merge :smirk:

**Comment by deletescape** [comment]
you wouldn't have had to close it, just pushing more to your branch would have added it to the PR lel

**Comment by pagaiba** [comment]
Yeah I know but closed it cause I realized that apparently the compressor I used fucked up a couple images, they were almost blank lol, so I don't think they can really be compressed any further

**Comment by deletescape** [comment]
Lel

**Pull request closed without merging**
