### PR TITLE
add screen rotation setting

### PR DESCRIPTION
**Pull request by 00raq00**

### CODE REVIEW

**Comment by nyancrimew** [comment]
This will not really work without the proper layouts for landscape and a lot of other code which has been removed for now

**Comment by 00raq00** [comment]
i've tested your activities with landscape orientation and it works fine. Off course I could overlook something. Blur'ing is fixed :)

**Comment by 00raq00** [comment]
If you want I can duplicate layouts for landscape and portrait rotation 😀 ( off course with fix for concrete orientation if it needs)

**Comment by nyancrimew** [comment]
Will merge this once conflicts are fixed

**Comment by 00raq00** [comment]
You could have written that there was a conflict. I would resolve conflicts or renew the pull request. 😀 :)

**Comment by 00raq00** [comment]
resolved conflicts :) sorry for whitespace diffs :(

**Pull request merged**
