### PR TITLE
Weather icon vectors

### PR DESCRIPTION
**Pull request by hassie-dash**
Added most weather icon vectors.

### CODE REVIEW

**Comment by AxiK101** [comment]
Preview?

_Sent from my Sony F3211 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hassie-dash** [comment]
@AxiK101 You can see the icons in the xxxhdpi drawable folder. They are the same icons from Google Weather. These are just the vector versions which can't be previewed.

**Comment by hassie-dash** [comment]
- [x] Clear - day
- [x] Clear - night
- [x] Partly cloudy - day
- [x] Partly cloudy - night
- [ ] Mostly cloudy - day
- [ ] Mostly cloudy - night
- [x] Cloudy
- [x] Rain
- [  ] Scattered showers - day
- [  ] Scattered showers - night
- [x] Snowy
- [x] Hazy
- [x] Flurry
- [x] Thunderstorms
- [x] Thundery
- [x] Unknown  
- [x] Windy

**Comment by nyancrimew** [comment]
We have another icon set by now, so I will close this PR, if you have the motivation to do your work again I'd be happy to accept a new PR as our current icon set is the final one (it might be extended by a bit though)

**Pull request closed without merging**
