### PR TITLE
added apps to categories

### PR DESCRIPTION
**Pull request by milindgoel15**
added three apps, two in games and other in entertainment

### CODE REVIEW

**Comment by milindgoel15** [comment]
👀

**Comment by nyancrimew** [comment]
@milindgoel15 I have some plans for how I wanna improve the auto categorization over all, I thought I'd get to it earlier which is why I hadn't merged this yet

**Comment by milindgoel15** [comment]
Oh 👍👍

**Comment by nift4** [comment]
The whole pr is messed up 🙄 @milindgoel15

**Comment by milindgoel15** [comment]
@nift4 cuz they begin merging but stop in between the merge due to new plans in launcher. It was clean before it xd

**Comment by nift4** [comment]
I know but in this State it cannot be merged anyway - it would be wise to recreate or close it.

**Pull request closed without merging**
