### PR TITLE
Remove fucking piracy check

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by amirzaidi** [comment]
99% sure this it not going to get merged

**Comment by LumenCeleste** [comment]
This PR is funny, do you think it will get merged anytime soon ? 
At first you wanted that Lawnchair doesn't hide apps, and now you even complain about the piracy check while Icon Pack Applying ? 
I mean it's the Dev's right to block piracy, because it's illegal.
Referring on pirate's logic, it's like to don't be allowed to defend yourself if someone attacks you.
To do something against piracy was a brave step by Lawnchair devs because I'm sure they know what shitstorm they will cause with that.

Literally Lawnchair just doesn't want that you commit a crime ;)

**Comment by nyancrimew** [comment]
No comment on this one.

**Comment by divadsn** [comment]
I'm leaving this here:
https://www.reddit.com/r/Android/comments/7azc2i/psa_lawnchair_launcher_now_with_more_censoring/dpgst0l

**Pull request closed without merging**
