### PR TITLE
Merge tag 'android-14.0.0_r21'

### PR DESCRIPTION
**Pull request by Goooler**
Re-merge #3945.

https://android.googlesource.com/platform/packages/apps/Launcher3/+/refs/tags/android-14.0.0_r21

### CODE REVIEW

**Comment by Goooler** [comment]
Few chagnes between r18 and r21, see https://github.com/Goooler/Launcher3/compare/android-14.0.0_r18...android-14.0.0_r21

**Comment by Goooler** [comment]
@MrSluffy Can we drop 2c43f69ba3a3ac637f1717bc2726c7c97b3ead01 and merge this?

**Comment by MrSluffy** [comment]
> @MrSluffy Can we drop [2c43f69](https://github.com/LawnchairLauncher/lawnchair/commit/2c43f69ba3a3ac637f1717bc2726c7c97b3ead01) and merge this?

We can, haven't fully check but please test it in A9 to A14 there's some faulty merge in this

example it reverts this 4276067c6c1fefd88253885e798c29313d6b4c85

**Comment by Goooler** [comment]
I just accept all changes from this branch, and picked up fa654851095890a092471af658dbbd4dbb751419 and e4de57a662b58748a25238942d629490073c6e00.

**Comment by MrSluffy** [comment]
> I just accept all changes from this branch, and picked up [fa65485](https://github.com/LawnchairLauncher/lawnchair/commit/fa654851095890a092471af658dbbd4dbb751419) and [e4de57a](https://github.com/LawnchairLauncher/lawnchair/commit/e4de57a662b58748a25238942d629490073c6e00).

I see that's why, you need to test it too

**Comment by Goooler** [comment]
Wired bad merge! Once you approve this, I'll merge it manually.

**Comment by MrSluffy** [comment]
It's ok now

**Pull request merged**
