### PR TITLE
Check `sIsConnected` before canceling notification

### LINKED ISSUE #2825: [BUG] Disallowed call from unknown notification listener
### Describe the bug

```
Lawnchair bug report 10.08.2022
Lawnchair version: 9.1 Alpha 3 (9012942)
version.release: 11
version.sdk_int: 30

error: Uncaught exception

--------- beginning of stacktrace
java.lang.SecurityException: Disallowed call from unknown notification listener: android.service.notification.INotificationListener$Stub$Proxy@8629470 class android.service.notification.INotificationListener$Stub$Proxy
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2376)
	at android.os.Parcel.createException(Parcel.java:2360)
	at android.os.Parcel.readException(Parcel.java:2343)
	at android.os.Parcel.readException(Parcel.java:2285)
	at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:4806)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:937)
	at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:914)
	at com.android.launcher3.notification.NotificationListener.onNotificationRankingUpdate(NotificationListener.java:298)
	at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2150)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: android.os.RemoteException: Remote stack trace:
	at com.android.server.notification.ManagedServices.checkServiceTokenLocked(ManagedServices.java:904)
	at com.android.server.notification.NotificationManagerService$10.getActiveNotificationsFromListener(NotificationManagerService.java:4240)
	at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:2182)
	at android.os.Binder.execTransactInternal(Binder.java:1162)
	at android.os.Binder.execTransact(Binder.java:1126)


```

### Steps to reproduce

1. Go to '...' lawnvhair

### Expected behavior

Don't throw exceptions 

### Screenshots

_No response_

### Device information

- Device: Android Smartphone
- OS:  Android version 11
- App version  9.1 Alpha 3 (9012942)

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Fixes #2825

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:white_check_mark: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Goooler** [comment]
@paphonb Let me know if there is a better solution.

**Comment by suphon-t** [comment]
The linked crash is in another method, and on an entirely different version of Lawnchair though. I'm not sure how this would fix it.

**Comment by Goooler** [comment]
I see, cause I've also observed this bug in the latest version

```
Fatal Exception: java.lang.SecurityException: Disallowed call from unknown notification listener: 
android.service.notification.INotificationListener$Stub$Proxy@16852a1 class android.service.notification.INotificationListener$Stub$Proxy
    at android.os.Parcel.readException(Parcel.java:2021)
    at android.os.Parcel.readException(Parcel.java:1967)
    at android.app.INotificationManager$Stub$Proxy.getActiveNotificationsFromListener(INotificationManager.java:2242)
    at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:886)
    at android.service.notification.NotificationListenerService.getActiveNotifications(NotificationListenerService.java:814)
    at sms.launcher.d$p02z.invokeSuspend(NotificationManager.kt:5)
    at wk.p01z.resumeWith(ContinuationImpl.kt:4)
    at pl.r0.run(DispatchedTask.kt:18)
    at ul.b.run(LimitedDispatcher.kt:2)
    at wl.a.run(Tasks.kt:1)
    at wl.p01z.d(CoroutineScheduler.kt:1)
    at wl.p01z$p03x.x044(CoroutineScheduler.kt:4)
    at wl.p01z$p03x.d(CoroutineScheduler.kt:4)
    at wl.p01z$p03x.run()
```

**Comment by Goooler** [comment]
See https://stackoverflow.com/questions/45428363/android-getactivenotifications-throws-securityexception

**Comment by Goooler** [comment]
Just merging this one, wait for some feedback.

**Comment by suphon-t** [comment]
@Goooler 
I still don't think that this PR will actually fix any of the crashes linked. I'll repeat again that the the checks you've added are around calls to `cancelNotification`, while all crashes linked are from calls to `getActiveNotifications`. Not to mention that three of them are reported from Lawnchair 9, and two of them are from 2017, so none of them are from Lawnchair 12.1. There's no evidence that this bug even exists in Lawnchair 12.1.

**Comment by Goooler** [comment]
@paphonb Cause I've observed similar crashes on the latest version.

**Comment by suphon-t** [comment]
> @paphonb Cause I've observed similar crashes on the latest version.

Then it would be better to create a new issue using the crash report from the latest version, and linking to that instead.

**Comment by Goooler** [comment]
I'll update the issue tomorrow.

**Comment by Goooler** [comment]
This PR might not be the right fix, I'm reverting now 69d29a6be1fac4d2721e2f123009c8e4303cba01.

**Comment by William150722** [comment]
@Goooler so how you fix this issues? Thanks.

**Comment by Goooler** [comment]
@William150722 It should work now, you can download APK from the latest commit.

**Comment by William150722** [comment]
@Goooler can i know which code you commit? Thanks

**Comment by Goooler** [comment]
Here 07183a63d8edac59c8b6c9f8c8a3e2d8e9161450.

**Comment by William150722** [comment]
@Goooler appreciate so much, thanks. Let me try it out.

**Pull request merged**
