### PR TITLE
Add permission ACCESS_RESTRICTED_SETTINGS

### PR DESCRIPTION
**Pull request by zjunior06**
This will allow modify restricted settings on Android 13

## Description

Fixes #(issue) 

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
✅ New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by suphon-t** [comment]
Does this actually have any effect? I don’t see the permission being mentioned in the documentation.

**Comment by zjunior06** [comment]
> Does this actually have any effect? I don’t see the permission being mentioned in the documentation.

Yes, it as, already tested and working.

**Comment by zjunior06** [comment]
Before:
Screenshot_20221015-052431


After:
Screenshot_20221015-052918_Settings

**Review by yasanglass — APPROVED** [review]

**Comment by daywalk3r666** [comment]
This don't work. Action build with this commit has no access to the permission.

**Comment by zjunior06** [comment]
> This don't work. Action build with this commit has no access to the permission.

You need allow it, App Info > 3-dots

**Comment by daywalk3r666** [comment]
Right but then you don't need this commit. Lawnchair alpha 4 can do this without this commit

**Comment by zjunior06** [comment]
> Right but then you don't need this commit. Lawnchair alpha 4 can do this without this commit

But new builds can't. (Dev builds)

**Comment by yasanglass** [comment]
@zjunior06 Thank you for contributing to _Lawnchair_!

**Pull request merged**
