### PR TITLE
add new strings.xml pt-rBR

### PR DESCRIPTION
**Pull request by ojuara1987**
Can I help with the Brazilian Portuguese translation?

### CODE REVIEW

**Comment by divadsn** [comment]
@ojuara1987 Please head over to Crowdin for translation

**Comment by ojuara1987** [comment]
@divadsn I already have the strings.xml pt-rBR translated as I publish? thank you

**Comment by fonix232** [comment]
@ojuara1987 We only use Crowdin for translations. Importing from other places would mean we'd have to import all the stuff back to Crowdin instead of using the already designed flow.

**Comment by ojuara1987** [comment]
@ fonix232 ok thanks, but how do I use the Crowdin need to install on the computer? I really wanted to help with the translation.

**Comment by bohrabhijeet** [comment]
@ojuara1987 You just need to make an account on Crowdin and go to translate.lawnchair.info in order to translate in your preferred language. You can access it from PC as well as mobile.

**Comment by ojuara1987** [comment]
@abhijeetbohra Ok I'll do it right now, thank you

**Pull request closed without merging**
