### PR TITLE
Add legacy backup support

### PR DESCRIPTION
**Pull request by suphon-t**

### CODE REVIEW

**Comment by Polomman** [comment]
This is for you paphonb you're fired from Lawnchair, or do you going to block me here too 😂 ...I just remind you that the world is free and be careful with karma ...

**Comment by nyancrimew** [comment]
@Polomman Please keep this topic out of here. GitHub is a developer platform to discuss anything directly related to the development of Lawnchair. Your personal issues with other developers do NOT belong here, if this happens again you will be banned from commenting on our GitHub repos aswell. 

Thanks for understanding

**Comment by Polomman** [comment]
No problem that's why I paid to use Nova Launcher, and remember that you
could not develop anything without the users so I better show grateful to
them. Also in the play store nobody is blocked for telling the truth ... so
if you are going to be in the play store, prepare to receive real comments
...

**Comment by Polomman** [comment]
Also I have my own Launcher in apk without bugs, lags or crashes ...

**Comment by divadsn** [comment]
@Polomman zero fucks given, kthxbye.

**Pull request merged**
