### PR TITLE
Migrate BaseActivity to AppCompat

### PR DESCRIPTION
**Pull request by Goooler**
## Description

Migrate the `BaseActivity` to `AppCompat` to better compat the changes in AndroidX libs in the future.

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Goooler** [comment]
```
OLD: Lawnchair 12.1.0 Dev (2bcd32d).apk (signature: V2)
NEW: Lawnchair 12.1.0 Dev (db8dbaf).apk (signature: V2)

          │            compressed            │           uncompressed
          ├───────────┬───────────┬──────────┼───────────┬───────────┬──────────
 APK      │ old       │ new       │ diff     │ old       │ new       │ diff
──────────┼───────────┼───────────┼──────────┼───────────┼───────────┼──────────
      dex │   4.7 MiB │   4.7 MiB │ +1,004 B │  11.3 MiB │  11.3 MiB │ +2.2 KiB
     arsc │   3.5 MiB │   3.5 MiB │      0 B │   3.5 MiB │   3.5 MiB │      0 B
 manifest │   5.5 KiB │   5.5 KiB │     -3 B │  24.3 KiB │  24.3 KiB │      0 B
      res │   1.9 MiB │   1.9 MiB │     +6 B │   3.1 MiB │   3.1 MiB │      0 B
   native │ 999.3 KiB │ 997.4 KiB │ -1.9 KiB │ 980.4 KiB │ 980.4 KiB │      0 B
    asset │  22.5 KiB │  22.4 KiB │     -7 B │  68.6 KiB │  68.6 KiB │    -13 B
    other │   1.6 KiB │   1.6 KiB │      0 B │     704 B │     704 B │      0 B
──────────┼───────────┼───────────┼──────────┼───────────┼───────────┼──────────
    total │  11.1 MiB │  11.1 MiB │   -988 B │  18.9 MiB │  18.9 MiB │ +2.1 KiB


         │          raw           │             unique
         ├────────┬────────┬──────┼───────┬───────┬─────────────────
 DEX     │ old    │ new    │ diff │ old   │ new   │ diff
─────────┼────────┼────────┼──────┼───────┼───────┼─────────────────
   files │      2 │      2 │    0 │       │       │
 strings │  69965 │  69991 │  +26 │ 62276 │ 62300 │ +24 (+71 -47)
   types │  19786 │  19791 │   +5 │ 17833 │ 17837 │  +4 (+44 -40)
 classes │  15923 │  15927 │   +4 │ 15923 │ 15927 │  +4 (+43 -39)
 methods │ 103838 │ 103867 │  +29 │ 98441 │ 98469 │ +28 (+634 -606)
  fields │  53673 │  53676 │   +3 │ 52896 │ 52899 │  +3 (+279 -276)


 ARSC    │ old  │ new  │ diff
─────────┼──────┼──────┼──────
 configs │  349 │  349 │  0
 entries │ 7485 │ 7485 │  0
```

**Review by suphon-t — CHANGES_REQUESTED** [review]
Let's not do this right now. I don't want to modify the base Launcher3 classes this much unless it's absolutely necessary. There aren't any benefits from doing the migration now, and we don't know what will break. Not to mention the efforts to merge new upstream changes.

**Comment by Goooler** [comment]
Actually, I'd tried out this change for a long time in my own launcher, seems it works well. I'm afraid with the updats of `core` and `compose` libs, more compact works need to be done in `LawnchairLauncher`, it's a little troublesome and easy to miss.

**Comment by Goooler** [comment]
```
OLD: Lawnchair 12.1.0 Dev (88c2e4e).apk (signature: V2)
NEW: Lawnchair 12.1.0 Dev (88170d7).apk (signature: V2)

          │            compressed            │           uncompressed
          ├───────────┬───────────┬──────────┼───────────┬───────────┬──────────
 APK      │ old       │ new       │ diff     │ old       │ new       │ diff
──────────┼───────────┼───────────┼──────────┼───────────┼───────────┼──────────
      dex │   4.7 MiB │   4.7 MiB │ +1.3 KiB │  11.3 MiB │  11.3 MiB │ +2.4 KiB
     arsc │   3.5 MiB │   3.5 MiB │      0 B │   3.5 MiB │   3.5 MiB │      0 B
 manifest │   5.5 KiB │   5.5 KiB │     -3 B │  24.3 KiB │  24.3 KiB │      0 B
      res │   1.9 MiB │   1.9 MiB │     +4 B │   3.1 MiB │   3.1 MiB │      0 B
   native │ 1,000 KiB │ 997.4 KiB │ -2.5 KiB │ 980.4 KiB │ 980.4 KiB │      0 B
    asset │  22.5 KiB │  22.4 KiB │     -5 B │  68.6 KiB │  68.6 KiB │    -11 B
    other │   1.6 KiB │   1.6 KiB │      0 B │     704 B │     704 B │      0 B
──────────┼───────────┼───────────┼──────────┼───────────┼───────────┼──────────
    total │  11.1 MiB │  11.1 MiB │ -1.3 KiB │  18.9 MiB │  18.9 MiB │ +2.4 KiB


         │          raw           │             unique
         ├────────┬────────┬──────┼───────┬───────┬─────────────────
 DEX     │ old    │ new    │ diff │ old   │ new   │ diff
─────────┼────────┼────────┼──────┼───────┼───────┼─────────────────
   files │      2 │      2 │    0 │       │       │
 strings │  69965 │  69991 │  +26 │ 62276 │ 62300 │ +24 (+71 -47)
   types │  19786 │  19791 │   +5 │ 17833 │ 17837 │  +4 (+44 -40)
 classes │  15923 │  15927 │   +4 │ 15923 │ 15927 │  +4 (+43 -39)
 methods │ 103838 │ 103867 │  +29 │ 98441 │ 98469 │ +28 (+629 -601)
  fields │  53669 │  53675 │   +6 │ 52892 │ 52898 │  +6 (+259 -253)


 ARSC    │ old  │ new  │ diff
─────────┼──────┼──────┼──────
 configs │  349 │  349 │  0
 entries │ 7485 │ 7485 │  0
```

**Comment by Goooler** [comment]
Just closing this now.

**Pull request closed without merging**
