### PR TITLE
F-Droid build flavor (WIP)

### PR DESCRIPTION
**Pull request by divadsn**
Re-opens #806

### CODE REVIEW

**Comment by divadsn** [comment]
To be upstreamed and updated with other build flavors.

**Comment by divadsn** [comment]
I think we are good for now, a fdroid flavor is already present in v2, so will close that.

**Comment by ildar** [comment]
Where?
https://github.com/LawnchairLauncher/Lawnchair/search?q=fdroid&unscoped_q=fdroid

**Comment by divadsn** [comment]
@ildar v2 sources aren't public yet

**Comment by ildar** [comment]
ah! ok, will try to follow up then.

**Pull request closed without merging**
