### PR TITLE
Add option to hide/size folder label

### LINKED ISSUE #3847: [FEATURE] DEV Version Add option to change the size/remove labels inside folders
### Describe the feature

I installed the DEV version (most recent one) and imported the backup from the alpha. The labels inside folders were huge and there was no option to reduce the size nor disable them. On telegram community channel it was said that the label folder, on the alpha version, would correspond to the home settings and that it didn't anymore.

### Why would it be useful to add?

To be able to change the size/remove labels inside folders.

### Did the feature exist in Lawnchair v2? (Play Store version)

Yes

### Example(s)

Add a setting inside the folder settings where you can toggle the labels and if enabled you can change the size of it.

### Additional context

_No response_

### LINKED ISSUE #3909: [FEATURE] In-folder shortcuts text resizing
### Describe the feature

As it is right now, shortcuts inside of homescreen folders are resized with the desktop shortcuts, but their text isn't. Let's add a slider to resize that as well, or hook it to the existing slider of homescreen label size.

### Why would it be useful to add?

Consistency. If I set my homescreen labels to 50%, my folders' insides are still at 100%, making them stand out way too much. And not fit in.

### Did the feature exist in Lawnchair v2? (Play Store version)

No

### Example(s)

Nova has a separate settings view for tuning in-folder icon sizes, so I can have in-folder labels at 50% and out-of-folder labels at 150%, if i want that for some reason.
изображение

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by MrSluffy**
## Description

- Closes : #3847
-  Closes : #3909

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Goooler** [comment]
There are 2 issues:
1. Disable this option, both folder and icon labels are disabled, we should explicit them.
2. Disable this option, the folder label is disabled when it's expanded but enabled when it's collapsed.

https://github.com/LawnchairLauncher/lawnchair/assets/10363352/4c05ae8a-cc10-4d9b-a926-0a0ffd4ffd8a

**Comment by MrSluffy** [comment]
> There are 2 issues:
> 
> 1. Disable this option, both folder and icon labels are disabled, we should explicit them.
> 2. Disable this option, the folder label is disabled when it's expanded but enabled when it's collapsed.
> 
>  Screen_recording_20231225_174056.mp4

hide label in workspace it's under homescreen

**Comment by MrSluffy** [comment]
> There are 2 issues:
> 
> 1. Disable this option, both folder and icon labels are disabled, we should explicit them.
> 2. Disable this option, the folder label is disabled when it's expanded but enabled when it's collapsed.
> 
>  Screen_recording_20231225_174056.mp4

That's not the requirement in feature request

**Comment by Goooler** [comment]
Follow up them.

**Comment by MrSluffy** [comment]
> Follow up them.

Can you create issue? Thanks

**Comment by Goooler** [comment]
It's #3916.

**Pull request merged**
