### PR TITLE
Update to conform to Material Design's style guide

### PR DESCRIPTION
**Pull request by Susexe**
## Description

I updated the strings.xml file to conform to Material Design's style guide. Here's what's changed:

- [Replaced title case](https://m3.material.io/foundations/content-design/style-guide/ux-writing-best-practices#fc5c2a78-f4bf-4d42-bdac-42ff80391129) with sentence case,
- [Removed punctuation](https://m3.material.io/foundations/content-design/style-guide/grammar-and-punctuation#555b17c7-de48-4974-8a82-51106899dc0e) where it's appropriate,
- [Added contractions](https://m3.material.io/foundations/content-design/style-guide/grammar-and-punctuation#be900a2b-7194-44e3-aee7-ac01f8cec9ca) in some places to avoid overly formal tone,
- [Added regular quotation marks](https://developers.google.com/style/quotation-marks#straight-and-curly-quotation-marks) to comply with Google's practice,
- [Removed ampersands](https://m3.material.io/foundations/content-design/style-guide/grammar-and-punctuation#5ed1c04f-6f41-4a5d-8315-a6f786488b4f) from body text and kept in titles,
- Rewritten some strings to sound more comprehendable.

The first change is probably the most controversial one, but I would like to know your stance on this. Personally, sentence case looks much better and more natural to me on mobile devices. See the diff for full changes.

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by SuperDragonXD** [comment]
Hey there,

Regarding Title Case, this was once implemented by two of our former team members due to its “visual prominence” and “a more symmetrical appearance”. It is also implemented with inspiration from Apple’s UX style guide, and so that’s why it stuck here.

If we were to change this, I’d first ask the team internally regarding their stance on this change. Afterwards, I'll update you regarding this.

(Personally, I also like Title Case for the labels/headings. I prefer sentence cade for the rest of the UI though.)

Otherwise, the PR looks good. It seems like I forgot to update some other descriptions to match M3 guidelines, so thanks for the catch.

**Comment by Susexe** [comment]
Thanks for the comment. Do let me know of your decision. I missed the following changes:
- `workspace_increase_max_grid_size_description` is missing an article _the_,
- `show_suggested_apps_at_drawer_top` is missing _app_ in _app drawer_,
- `max_suggestion_result_count_title` is missing _web_ in _web suggestions_.

While we're at it, could you add me as a proofreader for Serbian (Cyrillic) and Serbian (Latin) on Crowdin? I've been active there for a long time, and I am willing to maintain the translations. Also, there are some approved strings that need to be modified. My username is Rancher. Thanks.

**Comment by SuperDragonXD** [comment]
For the latter, sure ~~(it's been some time since I've touched Crowdin though, so it may take some time)~~ (i seem to lack permissions, requesting it as of now). I'll look into the former later.

**Review by SuperDragonXD — COMMENTED** [review]
After discussion with the team, it seems like they’re fine with the changes. However, regarding the three (3) strings above, I’d recommend keeping the original text for clarity. (As of now, haven’t gotten around to make all the strings more consistent with their `name` attribute)

Also regarding `Proofreader` permissions in Crowdin, I’ve added you there.

**Comment by Susexe** [comment]
Sorry for misusing this thread, but could you also add Bosnian and Croatian to Crowdin? I can work on them too (they are all part of the macrolanguage known as Serbo-Croatian).

By the way, I fully completed the Serbian translation.

**Comment by Susexe** [comment]
Sorry for misusing this thread, but could you also add Bosnian and Croatian to Crowdin? I can work on them too (they are all part of the macrolanguage known as Serbo-Croatian). Also, what's the status of this PR?

**Comment by SuperDragonXD** [comment]
I've added those languages to Crowdin. Also thanks for reminding me of this PR; I'll just apply some changes tommorow and merge it.

**Comment by 0xAbdiiii** [comment]
Not being so hasty but i think you forgot about this PR again.

**Review by SuperDragonXD — APPROVED** [review]
Looks like I forgot again (apologies for that). I'll make some other strings more consistent and update the documentation in a separate commit.

Thanks for your contribution to Lawnchair!

**Pull request merged**
