### PR TITLE
about: fix translators' dialog

### PR DESCRIPTION
**Pull request by chinmaykunkikar**
.setTitle() of Dialog didn't set title for the dialog. Instead use AlertDialog.builder.

Screenshots: https://imgur.com/a/pJ4Y3

### CODE REVIEW

**Review by nyancrimew — CHANGES_REQUESTED** [review]
The new design doesn't have any padding at the bottom anymore, I'd like to have it back as the dialog looks weird otherwise

**Comment by chinmaykunkikar** [comment]
@deletescape Let's see what can be done.
An 'OK' button (gravity=center) that dismisses the dialog at the end will add a padding as well.
Will do it if that's okay with you.

**Comment by nyancrimew** [comment]
Yeah sure, that sounds good

**Comment by chinmaykunkikar** [comment]
@deletescape https://imgur.com/3DhKFxV Looks good?

**Review by nyancrimew — APPROVED** [review]

**Pull request merged**
