### PR TITLE
Bing & Presearch Search Providers

### LINKED ISSUE #2654: [FEATURE REQUEST] Add search engine presearch
Please add Presearch.com to a list of available search engines.

### PR DESCRIPTION
**Pull request by yasanglass**
Adds [Bing](https://bing.com) & [Presearch](https://presearch.com/) as a new alternative search providers on Qsb (Closes #2654).

This uses the new `className` variable added on #2671 and is meant to be opened after #2671 is merged. This is going to be updated whenever #2671 is updated.

### CODE REVIEW

**Comment by yasanglass** [comment]
Added 6cea004fb9ad2b14aa8bf3f3484cb7ade8547abd that adds Bing QsbSearchProvider & am looking into adding even more if I find any other relevant search engines/websites/apps.

**Comment by DARTHPUNISHER** [comment]
> Added [6cea004](https://github.com/LawnchairLauncher/lawnchair/commit/6cea004fb9ad2b14aa8bf3f3484cb7ade8547abd) that adds Bing QsbSearchProvider & am looking into adding even more if I find any other relevant search engines/websites/apps.



> Added [6cea004](https://github.com/LawnchairLauncher/lawnchair/commit/6cea004fb9ad2b14aa8bf3f3484cb7ade8547abd) that adds Bing QsbSearchProvider & am looking into adding even more if I find any other relevant search engines/websites/apps.

What about Brave search? search.brave.com

**Comment by yasanglass** [comment]
@DARTHPUNISHER I'll look into it but I prefer not to promote Brave.

**Comment by DARTHPUNISHER** [comment]
> @DARTHPUNISHER I'll look into it but I prefer not to promote Brave.

The search engine is good you should research for it once and ya search engine works independently apart from browser, or if possible the option to add or own engine could also be useful.

**Comment by yasanglass** [comment]
Okay I'll look into it tomorrow and if I can make it work I'll add it to this PR.

**Comment by yasanglass** [comment]
Added [Sesame](https://play.google.com/store/apps/details?id=ninja.sesame.app.edge) search provider. The only issue is that, unlike other search providers, Sesame does not have a website. Currently, I just open the app's link on the Play Store. I am not really sure what is the best way of handling it so any ideas would be great.

**Comment by RikKoedoot** [comment]
Maybe making the option to select sesame gray when the app is not installed. Does this include the extra longpress icons menu options too?

**Comment by yasanglass** [comment]
@RikKoedoot I can do that but that requires more changes in the code & I thought maybe in some aspect this flow would be even better than that flow in terms of UX. I will look into it if you think it should be handled that way.

Also, Sesame instantly starts its search screen when opened from anywhere & there are many other search apps. I was wondering about maybe being able to open any app from the dock search bar would be useful for some use-cases. We can show the app icon on the bar. Although this requires much more changes and I would have to create a new PR for it later on.

About "the extra longpress icons menu options", I don't know what you're talking about

**Comment by DARTHPUNISHER** [comment]
@yasandev the extra long press option he's talking about is app shortcuts because that's a feature of sesame app and if that works they can even resolve the problem of app shortcuts not working on many devices. 
Tho what about brave search you considering that?

**Comment by yasanglass** [comment]
@DARTHPUNISHER then no, this just opens the Sesame app when the search bar is tapped + adds the Sesame logo on the search bar. Nothing more.

I did look into Brave search a bit and it does not work as simply as the ones I added in this PR yet. I think this PR is large enough already so I probably won't investigate it more at least for this PR.

**Comment by nonyonah** [comment]
But are you considering added the extra app shortcuts from sesame search because they are actually more useful than the default ones we have with more app support. Also can you make the search UI for sesame look like this? Make it in-built like the way Nova did it? Just wondering.
Screenshot_20220601-120256_Pixel Launcher

**Comment by yasanglass** [comment]
@nonyonah Not really. Those would require very customized code for Sesame specifically. This is a more general PR. I might improve the Sesame support later on in another PR.

**Comment by yasanglass** [comment]
I might just remove the Sesame support from this PR and add on a future PR since it already requires much more modifications and I prefer to create a PR just for Sesame alone so I can properly work on it and not just an extra thing.

**Comment by nonyonah** [comment]
> I might just remove the Sesame support from this PR and add on a future PR since it already requires much more modifications and I prefer to create a PR just for Sesame alone so I can properly work on it and not just an extra thing.

Yeah, I agree with you. Sesame integration requires a lot of code implementations and you need time to work on it. Great job though, I love the fact that you're helping the devs make this app better. It's very awesome, I'm a UI/UX designer, and if you need my input on anything about the app just let me know. Cheers.

**Comment by ThatOneCalculator** [comment]
Just saying, the ability to add *any* search engine would be great. (Especially for people who self-host metasearch engines)

**Comment by RikKoedoot** [comment]
Just an idea: maybe it would be better to just/also add a browser search option, like the chrome and edge searchbar widgets, then the users can use any search engine

**Comment by yasanglass** [comment]
Just removed the Sesame support from this PR but I am not sure if I have enough time and/or interest to invest in more advanced search-related PRs.

**Comment by yasanglass** [comment]
@patrykmichalik @paphonb ready for review now! I will try to add Sesame & more advanced search-related features in a future PR.

**Review by ghost — APPROVED** [review]

**Comment by ghost** [comment]
Thanks, @yasandev and @DariaHamrahPaytakht!

**Pull request merged**
