### PR TITLE
Center icons on workspace when hiding app names #1576

### PR DESCRIPTION
**Pull request by schokotets**
The implementation of centering folder icons vertically is not very clean because I wasn't able to find another easy way. I'm open to suggestions/edits.

### CODE REVIEW

**Comment by schokotets** [comment]
This is referencing issue #1576

**Comment by suphon-t** [comment]
Looks like setting [mCenterVertically](https://github.com/LawnchairLauncher/Lawnchair/blob/alpha/src/com/android/launcher3/BubbleTextView.java#L118) to true also achieves this. Can you try that?

**Comment by schokotets** [comment]
Thanks @paphonb, I'll look into it.

**Comment by RikKoedoot** [comment]
Closing because effort has been moved to v11

**Pull request closed without merging**
