### PR TITLE
Hide Dark Status Bar switch when status bar is hidden

### PR DESCRIPTION
**Pull request by RikKoedoot**
title says it all

### CODE REVIEW

**Comment by OmlineEditor** [comment]
is it possible to resolve conflicts and make improvements?

**Comment by RikKoedoot** [comment]
I think you can yes

**Comment by OmlineEditor** [comment]
but this is your code. can you fix it? do you know where the error is?

**Comment by RikKoedoot** [comment]
I'm a total noob when it comes to development, sorry. I'll ask patryk about it.

**Comment by ghost** [comment]
Thanks, @RikKoedoot!

**Pull request merged**
