### PR TITLE
Make BaseActivity extends ComponentActivity

### PR DESCRIPTION
**Pull request by Goooler**
## Description

We don't have to maintain ComponentActivity like behaviors in LawnchairLauncher anymore.

## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Review by SuperDragonXD — COMMENTED** [review]
Have you ensured that there aren't any major side-effects if we remove these? Seems like this PR could remove functionality that isn't available in `ComponentActivity`.

**Comment by Goooler** [comment]
I land this in my fork for a long time.

I've tried to replace it with `AppCompatActivity` in #3146, but it might not be a good choice. Now we can try `ComponentActivity` instead, which supports Lifecycle and Compose but AppCompat things.

**Review by MrSluffy — APPROVED** [review]
This is great, please merge it before weekend since merge A15 WIP it's not much change in launcher3 legacy

edit : I haven't test this in old android, it shouldn't be a problem in error like ResourceId not found thing?

**Comment by Goooler** [comment]
I guess resource id things should be related to AppCompat* instead of Component*.

**Comment by suphon-t** [comment]
> Seems like this PR could remove functionality that isn't available in `ComponentActivity`.

The additions I wrote are mostly for backporting `ComponentActivity`'s features, so this shouldn't be a problem. What I'm worried about is the additional features in `ComponentActivity` that the regular `Activity` doesn't have. But as @Goooler mentioned it's working in his fork, so that should be fine too.

**Review by suphon-t — APPROVED** [review]

**Pull request merged**
