### PR TITLE
Rename all modules to start with a lowercase

### PR DESCRIPTION
**Pull request by Goooler**
## Type of change

:white_check_mark: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by Goooler** [comment]
@suphon-t Any idea?

**Comment by suphon-t** [comment]
> @suphon-t Any idea?

I'm neutral on this.
Also don't forget to rename the usages in dependencies if you want to go ahead.

**Comment by Goooler** [comment]
> I'm neutral on this. Also don't forget to rename the usages in dependencies if you want to go ahead.

Yep, no need to change the project refs, cause they are refed by type-safe project accessors.

**Comment by suphon-t** [comment]
> Yep, no need to change the project refs, cause they are refed by type-safe project accessors.

Ah, nice. TIL.

**Pull request merged**
