### PR TITLE
Merged AOSP 13 QPR3

### PR DESCRIPTION
**Pull request by MrSluffy**
## Description
Initial AOSP 13 source merge to add support in android 13 it may break the existing feature but most of the existing feature works, it need a little of cleanup

There's new lib, the reason of this, is after I compile [LOS](https://wiki.lineageos.org/devices/sweet/build/variant1) the framework.jar some of the classes was distributed in the following jar, I tried to merge it in one .jar but there's an issue, it causing some classes abstract and classes not found so since it will not be merge in the apk only for compile

I maybe noob in PR, please if there's some changes need to be change please point it out to me so I can change it Thanks

New lib
seeder.jar
core.jar
core-all.jar
SystemUI-core.jar
framework-statsd.jar
android.jar

[iconloader ](https://github.com/MrSluffy/platform_frameworks_libs_systemui)

New Modules
[systemUIAnim]( https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android13-qpr3-release/packages/SystemUI/animation/)
[systemUIUnFold](https://android.googlesource.com/platform/frameworks/base/+/refs/heads/android13-qpr3-release/packages/SystemUI/unfold/)
[systemUIViewCapture](https://android.googlesource.com/platform/frameworks/libs/systemui/+/refs/heads/android13-qpr3-release/viewcapturelib/)

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
✅ Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by MrSluffy** [comment]
Oh my, renaming the module should fixed the build : [img](https://i.imgur.com/rUGhI6R.png)

**Comment by heckarman** [comment]
Widgets are broken in the debug build. Clicking in any of the widgets to interact crashes the launcher

**Comment by yasanglass** [comment]
Thank you for the PR, looks good in general but needs to be rebased and merged after #3695.

**Comment by yasanglass** [comment]
Merged manually. Thank you for your contribution. `13-dev` branch is now live but still in the early development stage.

**Comment by Goooler** [comment]
@MrSluffy 

Seems it's easy to merge 13.0.0 r83 in #3736, can we start a new PR to merge android-14.0.0_r15?

**Comment by MrSluffy** [comment]
> @MrSluffy
> 
> Seems it's easy to merge 13.0.0 r83 in #3736, can we start a new PR to merge android-14.0.0_r15?

We can start merge A14 once we finished 
#3728 compatibility to Q, R and S

**Comment by yasanglass** [comment]
Doing the A14 merge would be a good idea actually, instead of fixing things now and them getting broken again after the A14 merge.

**Comment by Goooler** [comment]
Yeah, we can merge A14 first, and fix compatibilities after.

**Comment by MrSluffy** [comment]
That make sense @Goooler @yasanglass , You can merge A14, my device doesn't have A14 atm so can't do it

**Comment by yasanglass** [comment]
I don't have an Android 14 device as well, might get it soon on my S22. Not sure how much actual testing is required for the merge though, its mainly just dealing with the conflicts.

**Comment by MrSluffy** [comment]
Got it, When my device get A14 I will start working on it

**Pull request closed without merging**
