### PR TITLE
Weather.com smartspace provider

### PR DESCRIPTION
**Pull request by ghost**
This is a barbarian cherry-pick from Librechair, with gratis API keys retrieved from the Weather.com website and application.

It might not work, since I can’t test this version as it uses outdated build scripts not compatible with the latest AGP. It should be rigorously tested before it is merged. 

    Explicit permission is granted for the Lawnchair team to unconditionally use all modifications in this merge request for any purpose whatsoever.

### CODE REVIEW

**Comment by nyancrimew** [comment]
This is absolutely impossible to merge and changes far too many things

**Comment by divadsn** [comment]
Can't you just use existing dependencies, like Google Gson?

**Comment by ghost** [comment]
> Can't you just use existing dependencies, like Google Gson?

I’m not sure what you’re talking about, since the Retrofit instance does use Gson

**Comment by ghost** [comment]
> This is absolutely impossible to merge and changes far too many things

I’m not sure how though, since I’ve just added an extra weather provider and optimized the smartspace preferences for more weather providers.

**Comment by ghost** [comment]
Gah! I see that the cherry pick has picked over some extra Librechair changes…

**Comment by nyancrimew** [comment]
@oldosfan Look at the diff. This breaks multiple existing classes because it's simply a blind cherry-pick. Code formatting rules have been changed as well and multiple useless dependencies have been added.

**Comment by ghost** [comment]
> @oldosfan Look at the diff. This breaks multiple existing classes because it's simply a blind cherry-pick. Code formatting rules have been changed as well and multiple useless dependencies have been added.

Exactly

I guess I’ll have to pay the price for lazyness

**Comment by ghost** [comment]
I’m on the train, so I tried to stuff a lot of stuff in while the train network was working

**Comment by ghost** [comment]
@deletescape By the way, I’ve updated the MR branch with some fixes that should hopefully make it better

**Pull request closed without merging**
