### PR TITLE
Implement Smartspacer as an alternative At a Glance provider

### PR DESCRIPTION
**Pull request by KieronQuinn**
## Description

This pull request integrates the Smartspacer Client SDK, following the [implementation guide](https://github.com/KieronQuinn/Smartspacer/wiki/9.-SDK:-Client-SDK-(for-Launchers)). 

As well as allowing native-quality access to Smartspacer (multiple pages, better support for many of the templates, the ability to long press pages), this would also allow Lawnchair users to access full At a Glance on Pixels, via Smartspacer.

The Smartspacer Client SDK was actually intended to be as simple to implement in Launcher3 based launchers as possible, and indeed contains code derived from Lawnchair, so that's why there's barely any code changes. The only potential issue I can see is the minSDK requirement - the SmartspaceMode `isAvailable` method does verify it's compatible, but since the library still requires a higher minSDK, `overrideLibrary` is required in the relevant manifest tags.

One thing you may wish to look at is the long press menu, which Smartspacer's Client SDK provides using the popular [Balloon library](https://github.com/skydoves/Balloon). This requires zero changes from a client perspective, but does differ from Lawnchair's styling:

image

If you wish to change this, the implementation guide has a section on doing so, but it would require implementation of a custom popup which can handle all the requirements.

Also, if #3559 gets implemented, Smartspacer provides a Discover Feed replacement, in the form of Expanded Smartspace. So long as the list of feeds isn't hardcoded, this should just work with no further changes.

## Type of change

:x: General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:white_check_mark: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Screenshots

image

image

image

image

### CODE REVIEW

**Comment by yasanglass** [comment]
Thank you for the PR, looks good in general but needs to be rebased and merged after https://github.com/LawnchairLauncher/lawnchair/pull/3695.

**Review by MrSluffy — APPROVED** [review]

**Comment by yasanglass** [comment]
@KieronQuinn we just created `13-dev` branch, please update the PR and it will be merged as soon as possible. There are a few minor conflicts after changing the base branch.

**Comment by yasanglass** [comment]
The PR looks good to me, just update the comments to have a space after the `//`. 

> If you wish to change this, the implementation guide has a section on doing so, but it would require implementation of a custom popup which can handle all the requirements.

It would be great if this could be included in this PR as well. We currently do not have resources to look into that just for this specific feature & Lawnchair has a pretty consistent UI overall.

And about #3559, I don't see that being implemented anytime soon unless it's by a third-party contributor, the core Lawnchair team currently does not have the resources to develop new major features.

**Comment by KieronQuinn** [comment]
Seems there's some issues with running it on the 13 branch, somehow the ViewBinding classes from the library are missing, looking into it now.

As for the style and Discover features, unfortunately I also do not have time to work on something like that for each launcher either. That's why the client plugin was intended to be drop in - minimal changes required (even if it doesn't exactly match the launcher style)

**Comment by KieronQuinn** [comment]
Was just a Proguard issue, should be good to go now

**Comment by Ravi-Kishor** [comment]
wow a great pr, waiting to mereged

**Comment by yasanglass** [comment]
Merged 🎉  thank you for your contribution to Lawnchair.

**Pull request merged**
