### PR TITLE
link various calendars to calendar icons

### PR DESCRIPTION
**Pull request by daywalk3r666**
## Description

Link simple calendar/pro , acalendar/+ , aosp calendar and etar to themed calendar 8cin
## Type of change

✅ : General change (non-breaking change that doesn't fit the below categories like copyediting)
:x: Bug fix (non-breaking change which fixes an issue)
:x: New feature (non-breaking change which adds functionality)
:x: Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by daywalk3r666** [comment]
It seema this isn't working. Only google calendar and clock get themed

**Comment by ABAAN-WEBDESIGNGEEK** [comment]
wouldn't it be better to do this in lawnicons?

**Comment by SuperDragonXD** [comment]
Nope. Lawnchair handles the dynamic icons, not Lawnicons. Lawnicons provides the static icons though 

Also re "this isn't working", the clock/calendar values are hardcoded. I'll make a patch soon allowing dynamic icons to other clock/calendar apps.

**Comment by daywalk3r666** [comment]
Ok thanks for info

**Comment by naveenccmsd** [comment]
@SuperDragonXD Did you started any work on clock/cal icon to othe oeam apps? Should I work on it if not started already?

**Comment by SuperDragonXD** [comment]
> @SuperDragonXD Did you started any work on clock/cal icon to othe oeam apps? Should I work on it if not started already?

I actually haven't worked on it yet. If you want, you can work on it; it'll be appreciated.

**Comment by naveenccmsd** [comment]
@SuperDragonXD , I applied patch to use same dynamic icons from google cal to other oem ,it was working. but later found that we are taking drawables from actual app insted of taking from lawnchair ie google clock itself , so It's not working if we uninstall google clock/cal app. 

I tried to reuse same code but somewhere it's broking, Should I goahed create separate override methods insted of existing one??

**Comment by SuperDragonXD** [comment]
You could create separate override methods if modifying the existing method does not work. Also you can incorporate your changes in a Draft PR, so that other people can see your changes and also tell you what to change in your code for it to work.

**Comment by daywalk3r666** [comment]
With this PR https://github.com/LawnchairLauncher/lawnchair/pull/3038 
Is my PR still needed?

**Comment by naveenccmsd** [comment]
Nope, I already added your calendar , so please close this pr

**Comment by SuperDragonXD** [comment]
Yeah, I think it's safe to close the PR. Also @naveenccmsd you can add the author of this PR as a co-author of your current PR.

**Pull request closed without merging**
