### PR TITLE
Added Simplified Chinese translation

### PR DESCRIPTION
**Pull request by ButaiKirin**

### CODE REVIEW

**Comment by divadsn** [comment]
Translations are done on [Crowdin](translate.lawnchair.app).

**Comment by ButaiKirin** [comment]
> Translations are done on [Crowdin](translate.lawnchair.app).

But you should know that the version of Lawnchair on Crowdin is V1, and most of translation were didn't works on v2. This is the translation of v2.

**Comment by nyancrimew** [comment]
@ZeroSimple V2 strings will be up on crowdin shortly

**Comment by ButaiKirin** [comment]
> @ZeroSimple V2 strings will be up on crowdin shortly

Hum... All right.

**Pull request closed without merging**
